blank_issues_enabled: false
contact_links:
  - name: Documentation Website
    about: Please read our documentation website before filing new issues.
    url: https://mochajs.org
  - name: Documentation Website > APIs
    about: If you're using Mocha's API, see also the website's API docs.
    url: https://mochajs.org/api
  - name: Gitter Chat
    about: Our chat room is the right place for quick informal questions.
    url: http://gitter.im/mochajs/mocha
  - name: StackOverflow
    about: For more questions, see the `mocha` tag on StackOverflow.
    url: https://stackoverflow.com/questions/tagged/mocha
